server:
  port: ${PORT}
  proxied: true

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            title: System Design
            limit: 15
            collapse-after: 5
            cache: 12h
            feeds:
              - url: https://arpitbhayani.me/blogs/feed.xml
                title: Arpit Bhayani
              - url: https://arpit.substack.com/feed
                title: Arpit Newsletter
              - url: https://newsletter.pragmaticengineer.com/feed
                title: Pragmatic Engineer
              - url: https://blog.bytebytego.com/feed
                title: ByteByteGo
              - url: https://newsletter.systemdesign.one/feed
                title: System Design (Neo Kim)
              - url: https://designgurus.substack.com/feed
                title: System Design Nuggets
              - url: https://architecturenotes.co/feed
                title: Architecture Notes
              - url: https://martinfowler.com/feed.atom
                title: Martin Fowler

          - type: rss
            title: Substack
            limit: 12
            collapse-after: 4
            cache: 12h
            feeds:
              - url: https://yewjin.substack.com/feed
                title: What YJ Thinks
              - url: https://koffeeguy.substack.com/feed
                title: Karan Dhir
              - url: https://shreyasdoshi.substack.com/feed
                title: Shreyas Doshi
              - url: https://cutlefish.substack.com/feed
                title: The Beautiful Mess

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UC_b1GUJv_2QiMP4BxC9-Dxg # Arpit Bhayani
              - UC2D2CMWXMOVWx7giW1n3LIg # Andrew Huberman
              - UCJY3HORlEGL1YRlcffpBBaw # Mikey Posada
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

      - size: small
        widgets:
          - type: weather
            location: Bengaluru, India
            units: metric
            hour-format: 12h

          - type: markets
            markets:
              - symbol: ^NSEI
                name: Nifty 50
              - symbol: ^BSESN
                name: Sensex
              - symbol: RELIANCE.NS
                name: Reliance
              - symbol: TCS.NS
                name: TCS
              - symbol: INFY.NS
                name: Infosys
              - symbol: HDFCBANK.NS
                name: HDFC Bank

          - type: repository
            title: Papertrail
            repository: ankitchouhan1020/papertrail
            pull-requests-limit: 3
            issues-limit: 3
            commits-limit: 5
